#!/usr/bin/env python3
"""
Analyze one MuJoCo peg-in-hole HDF5 episode.

Input:
    episode.hdf5 generated by mujoco_hdf5_recorder.py

Outputs:
    quality_report.txt
    task_errors.png
    force_torque.png
    force_magnitude.png
    joint_tracking.png
    joint_tracking_error.png
    contact_timeline.png
    ee_and_peg_position.png
    image_stream_check.txt
    optional preview_video.mp4

Usage:
    python3 scripts/analyze_mujoco_hdf5_episode.py \
        --episode data/peg_in_hole_hdf5/20260528_153012_teleop/episode.hdf5

Notes:
    - All analysis uses MuJoCo simulation time.
    - The script does not assume state/force/image streams have the same length.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, List, Tuple

import h5py
import numpy as np
import matplotlib.pyplot as plt


def read_arr(f: h5py.File, path: str, default=None):
    if path in f:
        return f[path][:]
    return default


def decode_str_array(arr) -> List[str]:
    if arr is None:
        return []
    out = []
    for x in arr:
        if isinstance(x, bytes):
            out.append(x.decode("utf-8"))
        else:
            out.append(str(x))
    return out


def finite_stats(x: np.ndarray) -> Dict[str, float]:
    x = np.asarray(x)
    mask = np.isfinite(x)
    if not np.any(mask):
        return {
            "min": math.nan,
            "max": math.nan,
            "mean": math.nan,
            "std": math.nan,
            "median": math.nan,
        }
    xf = x[mask]
    return {
        "min": float(np.min(xf)),
        "max": float(np.max(xf)),
        "mean": float(np.mean(xf)),
        "std": float(np.std(xf)),
        "median": float(np.median(xf)),
    }


def stream_rate_report(t: np.ndarray, name: str) -> List[str]:
    lines = []
    t = np.asarray(t, dtype=float)
    lines.append(f"[{name}] samples: {len(t)}")
    if len(t) < 2:
        lines.append(f"[{name}] not enough samples for rate estimation")
        return lines

    dt = np.diff(t)
    dt_pos = dt[dt > 0]
    lines.append(f"[{name}] t range: {t[0]:.6f} -> {t[-1]:.6f} s, duration: {t[-1] - t[0]:.6f} s")

    if len(dt_pos) == 0:
        lines.append(f"[{name}] ERROR: no positive timestamp intervals")
        return lines

    med_dt = float(np.median(dt_pos))
    mean_dt = float(np.mean(dt_pos))
    med_hz = 1.0 / med_dt if med_dt > 0 else math.nan
    mean_hz = 1.0 / mean_dt if mean_dt > 0 else math.nan

    lines.append(f"[{name}] median dt: {med_dt:.6f} s, median rate: {med_hz:.2f} Hz")
    lines.append(f"[{name}] mean dt:   {mean_dt:.6f} s, mean rate:   {mean_hz:.2f} Hz")
    lines.append(f"[{name}] max dt:    {float(np.max(dt_pos)):.6f} s")

    n_nonmono = int(np.sum(dt <= 0))
    if n_nonmono > 0:
        lines.append(f"[{name}] WARNING: non-monotonic or duplicate timestamps: {n_nonmono}")
    else:
        lines.append(f"[{name}] timestamps monotonic: OK")

    # Simple jitter indicator relative to median interval.
    if med_dt > 0:
        large_gap = np.sum(dt_pos > 1.5 * med_dt)
        lines.append(f"[{name}] gaps > 1.5x median dt: {int(large_gap)}")

    return lines


def count_nan(name: str, arr: np.ndarray) -> str:
    arr = np.asarray(arr)
    n = arr.size
    if n == 0:
        return f"{name}: empty"
    k = int(np.sum(~np.isfinite(arr)))
    pct = 100.0 * k / n
    return f"{name}: NaN/Inf {k}/{n} ({pct:.3f}%)"


def first_true_time(t: np.ndarray, flag: np.ndarray):
    if t is None or flag is None or len(t) == 0 or len(flag) == 0:
        return None
    idx = np.where(flag > 0.5)[0]
    if len(idx) == 0:
        return None
    return float(t[idx[0]])


def plot_task_errors(out_dir: Path, t_state, align_state, ins_state, t_force, align_force, ins_force, contact_t):
    plt.figure(figsize=(10, 5))
    if t_state is not None and align_state is not None and len(t_state):
        plt.plot(t_state, align_state, label="align_err_xz state")
    if t_force is not None and align_force is not None and len(t_force):
        plt.plot(t_force, align_force, label="align_err_xz force-sampled")
    if t_state is not None and ins_state is not None and len(t_state):
        plt.plot(t_state, ins_state, label="insertion_err_y state")
    if contact_t is not None:
        plt.axvline(contact_t, linestyle="--", label="first peg contact")
    plt.xlabel("simulation time (s)")
    plt.ylabel("error (m)")
    plt.title("Peg-hole task errors")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "task_errors.png", dpi=180)
    plt.close()


def plot_force(out_dir: Path, t_force, ft, contact_t):
    if t_force is None or ft is None or len(t_force) == 0:
        return

    force = ft[:, :3]
    torque = ft[:, 3:6]
    force_mag = np.linalg.norm(force, axis=1)
    torque_mag = np.linalg.norm(torque, axis=1)

    plt.figure(figsize=(10, 5))
    plt.plot(t_force, force[:, 0], label="Fx")
    plt.plot(t_force, force[:, 1], label="Fy")
    plt.plot(t_force, force[:, 2], label="Fz")
    if contact_t is not None:
        plt.axvline(contact_t, linestyle="--", label="first peg contact")
    plt.xlabel("simulation time (s)")
    plt.ylabel("force")
    plt.title("Force components")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "force_torque.png", dpi=180)
    plt.close()

    plt.figure(figsize=(10, 5))
    plt.plot(t_force, force_mag, label="|F|")
    plt.plot(t_force, torque_mag, label="|T|")
    if contact_t is not None:
        plt.axvline(contact_t, linestyle="--", label="first peg contact")
    plt.xlabel("simulation time (s)")
    plt.ylabel("magnitude")
    plt.title("Force and torque magnitudes")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "force_magnitude.png", dpi=180)
    plt.close()


def plot_joint(out_dir: Path, t_state, qpos, qcmd, qtarget):
    if t_state is None or qpos is None or len(t_state) == 0:
        return

    plt.figure(figsize=(10, 5))
    for j in [0, 3, 6]:
        if qpos.shape[1] > j:
            plt.plot(t_state, qpos[:, j], label=f"q{j+1}")
        if qcmd is not None and qcmd.shape[1] > j:
            plt.plot(t_state, qcmd[:, j], linestyle="--", label=f"q_cmd{j+1}")
    plt.xlabel("simulation time (s)")
    plt.ylabel("joint angle (rad)")
    plt.title("Representative joint tracking")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "joint_tracking.png", dpi=180)
    plt.close()

    if qcmd is not None and qcmd.shape == qpos.shape:
        err_cmd = np.linalg.norm(qcmd - qpos, axis=1)
        plt.figure(figsize=(10, 5))
        plt.plot(t_state, err_cmd, label="||q_cmd - q||")
        if qtarget is not None and qtarget.shape == qpos.shape:
            err_target = np.linalg.norm(qtarget - qpos, axis=1)
            plt.plot(t_state, err_target, label="||q_target - q||")
        plt.xlabel("simulation time (s)")
        plt.ylabel("joint error norm (rad)")
        plt.title("Joint tracking error")
        plt.legend()
        plt.tight_layout()
        plt.savefig(out_dir / "joint_tracking_error.png", dpi=180)
        plt.close()


def plot_contact(out_dir: Path, t_force, contact, min_dist):
    if t_force is None or contact is None or len(t_force) == 0:
        return

    plt.figure(figsize=(10, 5))
    plt.plot(t_force, contact, label="peg_contact")
    if min_dist is not None and len(min_dist) == len(t_force):
        plt.plot(t_force, min_dist, label="peg_contact_min_dist")
    plt.xlabel("simulation time (s)")
    plt.ylabel("contact flag / distance")
    plt.title("Contact timeline")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "contact_timeline.png", dpi=180)
    plt.close()


def plot_positions(out_dir: Path, t_state, ee_pose, peg_tip, hole_center):
    if t_state is None or len(t_state) == 0:
        return

    plt.figure(figsize=(10, 5))
    if ee_pose is not None and len(ee_pose):
        plt.plot(t_state, ee_pose[:, 0], label="ee x")
        plt.plot(t_state, ee_pose[:, 1], label="ee y")
        plt.plot(t_state, ee_pose[:, 2], label="ee z")
    if peg_tip is not None and len(peg_tip):
        plt.plot(t_state, peg_tip[:, 0], linestyle="--", label="peg tip x")
        plt.plot(t_state, peg_tip[:, 1], linestyle="--", label="peg tip y")
        plt.plot(t_state, peg_tip[:, 2], linestyle="--", label="peg tip z")
    plt.xlabel("simulation time (s)")
    plt.ylabel("position (m)")
    plt.title("End-effector and peg-tip position")
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_dir / "ee_and_peg_position.png", dpi=180)
    plt.close()


def inspect_images(f: h5py.File, episode_dir: Path, out_dir: Path) -> List[str]:
    lines = []
    if "observations/images/camera_names" not in f:
        lines.append("No image metadata found.")
        return lines

    cams = decode_str_array(f["observations/images/camera_names"][:])
    lines.append(f"Camera streams: {cams}")

    for cam in cams:
        base = f"observations/images/{cam}"
        if f"{base}/timestamps" not in f or f"{base}/file_paths" not in f:
            lines.append(f"[{cam}] missing timestamps or file_paths")
            continue

        ts = f[f"{base}/timestamps"][:]
        paths = decode_str_array(f[f"{base}/file_paths"][:])
        lines.extend(stream_rate_report(ts, f"image/{cam}"))

        missing = 0
        for p in paths:
            if not (episode_dir / p).exists():
                missing += 1
        lines.append(f"[image/{cam}] files: {len(paths)}, missing: {missing}")

    with (out_dir / "image_stream_check.txt").open("w", encoding="utf-8") as g:
        g.write("\n".join(lines))
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--episode", required=True, help="Path to episode.hdf5")
    parser.add_argument("--out", default=None, help="Output analysis directory")
    args = parser.parse_args()

    episode_path = Path(args.episode).expanduser().resolve()
    if not episode_path.exists():
        raise FileNotFoundError(episode_path)

    episode_dir = episode_path.parent
    out_dir = Path(args.out).expanduser().resolve() if args.out else episode_dir / "analysis"
    out_dir.mkdir(parents=True, exist_ok=True)

    report = []
    report.append(f"Episode: {episode_path}")
    report.append(f"Episode dir: {episode_dir}")
    report.append("")

    with h5py.File(episode_path, "r") as f:
        report.append("=== Root attributes ===")
        for k, v in f.attrs.items():
            report.append(f"{k}: {v}")
        report.append("")

        t_state = read_arr(f, "timestamps/state")
        t_force = read_arr(f, "timestamps/force")
        t_image = read_arr(f, "timestamps/image")

        report.append("=== Stream timing ===")
        if t_state is not None:
            report.extend(stream_rate_report(t_state, "state"))
        if t_force is not None:
            report.extend(stream_rate_report(t_force, "force"))
        if t_image is not None:
            report.extend(stream_rate_report(t_image, "image_all"))
        report.append("")

        qpos = read_arr(f, "observations/qpos")
        qvel = read_arr(f, "observations/qvel")
        ee_pose = read_arr(f, "observations/ee_pose")
        peg_tip = read_arr(f, "observations/peg_tip_pos")
        hole_center = read_arr(f, "observations/hole_center_pos")
        ft = read_arr(f, "observations/force_torque")
        qcmd = read_arr(f, "actions/q_cmd")
        qtarget = read_arr(f, "actions/q_target")

        align_state = read_arr(f, "task/state_align_err_xz")
        ins_state = read_arr(f, "task/state_insertion_err_y")
        align_force = read_arr(f, "task/force_align_err_xz")
        ins_force = read_arr(f, "task/force_insertion_err_y")

        contact_force = read_arr(f, "contact/force_peg_contact")
        min_dist_force = read_arr(f, "contact/force_peg_contact_min_dist")

        report.append("=== NaN / Inf checks ===")
        for name, arr in [
            ("qpos", qpos),
            ("qvel", qvel),
            ("ee_pose", ee_pose),
            ("peg_tip_pos", peg_tip),
            ("hole_center_pos", hole_center),
            ("force_torque", ft),
            ("q_cmd", qcmd),
            ("q_target", qtarget),
            ("state_align_err_xz", align_state),
            ("force_align_err_xz", align_force),
        ]:
            if arr is not None:
                report.append(count_nan(name, arr))
        report.append("")

        report.append("=== Task metrics ===")
        if align_state is not None and len(align_state):
            s = finite_stats(align_state)
            report.append(f"state_align_err_xz min/median/max: {s['min']:.6f} / {s['median']:.6f} / {s['max']:.6f} m")
        if ins_state is not None and len(ins_state):
            s = finite_stats(ins_state)
            report.append(f"state_insertion_err_y min/median/max: {s['min']:.6f} / {s['median']:.6f} / {s['max']:.6f} m")
        if ft is not None and len(ft):
            force_mag = np.linalg.norm(ft[:, :3], axis=1)
            torque_mag = np.linalg.norm(ft[:, 3:6], axis=1)
            fs = finite_stats(force_mag)
            ts = finite_stats(torque_mag)
            report.append(f"force magnitude min/median/max: {fs['min']:.3f} / {fs['median']:.3f} / {fs['max']:.3f}")
            report.append(f"torque magnitude min/median/max: {ts['min']:.3f} / {ts['median']:.3f} / {ts['max']:.3f}")

            if t_force is not None and len(t_force) == len(force_mag):
                imax = int(np.nanargmax(force_mag))
                report.append(f"peak force time: {float(t_force[imax]):.6f} s")

        contact_t = first_true_time(t_force, contact_force)
        report.append(f"first peg contact time: {contact_t if contact_t is not None else 'None'}")
        report.append("")

        report.append("=== Event markers ===")
        if "events/names" in f:
            names = decode_str_array(f["events/names"][:])
            te = f["events/t_episode"][:] if "events/t_episode" in f else []
            for i, name in enumerate(names):
                tt = float(te[i]) if i < len(te) else math.nan
                report.append(f"{i}: {name} @ t_episode={tt:.6f}s")
        else:
            report.append("No events group found.")
        report.append("")

        report.append("=== Image stream check ===")
        report.extend(inspect_images(f, episode_dir, out_dir))
        report.append("")

        plot_task_errors(out_dir, t_state, align_state, ins_state, t_force, align_force, ins_force, contact_t)
        plot_force(out_dir, t_force, ft, contact_t)
        plot_joint(out_dir, t_state, qpos, qcmd, qtarget)
        plot_contact(out_dir, t_force, contact_force, min_dist_force)
        plot_positions(out_dir, t_state, ee_pose, peg_tip, hole_center)

    report_path = out_dir / "quality_report.txt"
    report_path.write_text("\n".join(report), encoding="utf-8")

    print(f"Analysis saved to: {out_dir}")
    print(f"Report: {report_path}")


if __name__ == "__main__":
    main()
