# Data Recording
record_data: false
record_dir: "/home/stw/pangu/src/arm_teleop/data/peg_in_hole"
record_force_hz: 500.0
record_state_hz: 30.0
record_all_500hz: true


# HDF5 recording
record_hdf5: true
hdf5_record_dir: "/home/stw/pangu/src/arm_teleop/data/peg_in_hole_hdf5"

hdf5_force_hz: 500.0
hdf5_state_hz: 30.0
hdf5_image_hz: 30.0

hdf5_record_images: true
hdf5_camera_names:
  - "ee_cam"
  - "base_top_cam"

hdf5_image_width: 640
hdf5_image_height: 480
hdf5_image_format: "hdf5_rgb"
hdf5_jpg_quality: 90

hdf5_auto_start: false
hdf5_episode_label: "teleop"
hdf5_max_buffer_rows: 500000

# ROS service for data recording
enable_recording_service: true
recording_service_name: "/mujoco_hdf5_recording/set_recording"

# Mujoco配置
# mujoco_model_path: "/home/stw/pangu/src/arm_teleop/model/right_arm_peg_tool.xml"
# mujoco_model_path: "/home/stw/pangu/src/arm_teleop/model/right_arm_peg_tool_wall.xml"
mujoco_model_path: "/home/stw/pangu/src/arm_teleop/model/pangu_all_right.xml"
enable_hand: false
enable_visual_guides: false
cctv_camera: "cctv_cam"

# VisionPro配置
vp_ip: "192.168.1.144" # DaiLab-Normal
vp_record: false  # 是否记录VisionPro数据流
# vuer: true
vuer: false


# 末端执行器选择: none, hand, gripper, peg
end_effector: "peg"

# 机械臂遥控参数
arm_config:
  leftright: "right" # 指定使用人的哪只手的位姿来操控
  # move: false
  
  scaling_factor: 1.5
  smoothing_factor: 0.99
  update_frequency: 0.01 # 根据日志，每秒能发送80个控制指令，也就是每一次操控，除开sleep了0.01秒，计算开销时间应该是 1/80 - 0.01 = 0.0025s
  position_logging_interval: 0.1  # 位置日志记录间隔(秒)

  # 启用自适应控制
  use_adaptive_control: false
  
  # 自适应控制参数
  adaptive_config:
    leftright: "right"
    window_size: 10  # 运动历史窗口大小
    velocity_threshold: 0.15  # 快速移动阈值 (m/s)
    precision_threshold: 0.005  # 精细操作阈值 (m)
    smoothing_range: [0.5, 0.5]  # 平滑系数范围
    scaling_range: [1.0, 1.0]  # 缩放系数范围

  # 位置范围限制
  x_range: [-0.5, 0.3]
  y_range: [0.25, 1.4]
  z_range: [-0.5, 0.5]
  # 旋转范围限制 (弧度制)
  limit_rotation: true  # 启用旋转限制
  rx_range: [2, 3.14]  # rx旋转范围
  ry_range: [0, 1.5]  # ry旋转范围
  rz_range: [-2.7, 0]  # rz旋转范围

# VisionPro手部控制配置
hand_control:
  use_right_hand: true  # 使用右手控制

# 灵巧手参数
hand_config:
  smoothing_factor: 0.6
  update_frequency: 0.01
  max_hand_range: 65535
  hand_speed: 1000  # 灵巧手最大速度 (1-1000)

# 夹爪参数
gripper_config:
  leftright: "right"
  max_width: 1000
  update_frequency: 0.001
  grip_sensitivity: 0.7
  default_speed: 100  # 夹爪默认速度 (1-100)
  # 手势检测参数
  grip_activation_threshold: 0.3  # 激活抓取的阈值
  grip_release_threshold: 0.6  # 释放抓取的阈值

# 日志配置
logging:
  console_level: "info"
  file_level: "info"
  max_file_size: 104857600  # 最大日志文件大小 (100MB)
  backup_count: 5  # 备份日志文件数量
  log_prefix: "mujoco" # pangu or mujoco